=== cacalos/JTEtest/usmsf_map/data/data_sig/dict/dictionary.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- dictionary configuration -->
<!ELEMENT dictionary (parser, display, vendor*, typedef*, error*, avp*, base, application*)>
     
<!-- uDIAMETER message parser option configuration 값 -->
<!ELEMENT parser (version, no_check_header_flag, check_unknown_cmd, check_unknown_avp,
				check_mandatory_avp_length, check_empty_group, check_avprule,
				check_required_length)>
<!ATTLIST parser
	version CDATA #IMPLIED <!-- DIAMETER message version (default : 1) -->
	<!-- DIAMETER Message Header Flag bits 값 오류를 체크하지 않는다. (default : no) -->
	no_check_header_flag ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- Unknown command 전달되었음을 체크할 것인지 여부 (default : no) -->
	check_unknown_cmd ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- Unknown AVP가 전달되었음 체크할 것인지 여부 (default : no) -->
	check_unknown_avp ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- Mandatory AVP의 길이가 0인지 체크할것인지 여부 (default : no) -->
	check_mandatory_avp_length ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- group이 empty일 경우 에러를 발생시킬 것인지 여부 (default : no) -->
	check_empty_group ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- avp rule을 사용해 avplist를 검증할 것인지 여부 (default : no) -->
	check_avprule ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- required AVP의 길이가 0인지 체크할것인지 여부 (default : no) -->
	check_required_length ("yes" | "no" | "true" | "false" | "on" | "off") "no"
>
<!ELEMENT version (#PCDATA)> <!-- DIAMETER message version (default : 1) -->
<!ELEMENT no_check_header_flag (#PCDATA)> <!-- DIAMETER Message Header Flag bits 값 오류를 체크하지 않는다. (default : no) -->
<!ELEMENT check_unknown_cmd (#PCDATA)> <!-- Unknown command 전달되었음을 체크할 것인지 여부 (default : no) -->
<!ELEMENT check_unknown_avp (#PCDATA)> <!-- Unknown AVP가 전달되었음 체크할 것인지 여부 (default : no) -->
<!ELEMENT check_mandatory_avp_length (#PCDATA)> <!-- Mandatory AVP의 길이가 0인지 체크할것인지 여부 (default : no) -->
<!ELEMENT check_empty_group (#PCDATA)> <!-- group이 empty일 경우 에러를 발생시킬 것인지 여부 (default : no) -->
<!ELEMENT check_avprule (#PCDATA)> <!-- avp rule을 사용해 avplist를 검증할 것인지 여부 (default : no) -->
<!ELEMENT check_required_length (#PCDATA)> <!-- required AVP의 길이가 0인지 체크할것인지 여부 (default : no) -->

<!-- uDIAMETER message display option --> 
<!ELEMENT display (tabsize, octnbline, octflags, timeformat)>,
<!ATTLIST display
	tabsize CDATA #IMPLIED <!-- avp depth 별 tab 크기 (default : 0 [TAB 사용])-->
	octnbline CDATA #IMPLIED <!-- octet의 한줄당 byte 출력 개수 (default : 16) -->
	<!-- octet 출력 flags (0x01: number disable, 0x02: ascii disable, 0x04: newline char)  (default : 0x03) -->
	octflags CDATA #IMPLIED
	<!-- time value 출력 format. 특수 문자가 들어가므로 CDATA로 표기할 것을 권함 (default : %Y-%m-%dT%H:%H:%S) -->
	timeformat CDATA #IMPLIED
>
<!ELEMENT tabsize EMPTY> <!-- avp depth 별 tab 크기 (default : 0 [TAB 사용])-->
<!ELEMENT octnbline EMPTY> <!-- octet의 한줄당 byte 출력 개수 (default : 16) --> 
<!-- octet 출력 flags (0x01: number disable, 0x02: ascii disable, 0x04: newline char)  (default : 0x03) -->
<!ELEMENT octflags EMPTY> 
<!-- time value 출력 format. 특수 문자가 들어가므로 CDATA로 표기할 것을 권함 (default : %Y-%m-%dT%H:%H:%S) -->
<!ELEMENT timeformat EMPTY>

<!-- vendor id 정보 -->
<!ELEMENT vendor EMPTY>
<!ATTLIST vendor
	id CDATA #REQUIRED <!-- vendor id (ex: 10415) -->
	name CDATA #REQUIRED <!-- vendor name (ex: 3GPP) -->
>

<!-- type definition 정보 --> 
<!ELEMENT typedef EMPTY>
<!ATTLIST typedef
	name ID #REQUIRED <!-- type 이름 -->
	parent IDREF #IMPLIED <!-- 부모 type 이름 -->
>

<!-- error definition 정보 --> 
<!ELEMENT error EMPTY>
<!ATTLIST error
	code CDATA #REQUIRED <!-- error code -->
	name ID #REQUIRED <!-- error 이름 -->
>

<!-- AVP definition 정보 -->
<!ELEMENT avp ((type | grouped | enumerated))>
<!ATTLIST avp
	name ID #REQUIRED <!-- AVP 이름 -->
	code CDATA #REQUIRED <!-- AVP code -->
	vendor_id CDATA #IMPLIED <!-- AVP vendor id -->
	mandatory (must | may | mustnot | shouldnot) "may" <!-- mandatory 여부 -->
	protected (must | may | mustnot | shouldnot) "may" <!-- protected 여부 -->
	<!-- 출력 옵션 (hexstr: STRING일 경우 HEX값 형태로 출력, hexval: 출력 시 HEX 값도 같이 출력,
			rsltcode : 해당 int 값의 result code 이름도 같이 출력)  -->
	display (default | hexstr | hexval | rsltcode) "default"
	description CDATA #IMPLIED <!-- avp 에 대한 설명 -->
>
<!-- AVP type 정보 -->
<!ELEMENT type EMPTY>
<!ATTLIST type
	name IDREF #REQUIRED <!-- AVP type 이름 -->
>
<!-- AVP group 타입에 구조 정보 -->
<!ELEMENT grouped (fixed*, required*, optional*)>
<!-- AVP enumerated 타입에 대한 정보 -->
<!ELEMENT enumerated (enum*)>
<!-- AVP enum 멤버에 대한 정보 -->
<!ELEMENT enum EMPTY>
<!ATTLIST enum
	name CDATA #REQUIRED <!-- enum name -->
	code CDATA #IMPLIED <!-- enum code value -->
>

<!-- request message 구조 정보 -->
<!ELEMENT requestrules (fixed*, required*, optional*)>
<!-- answer message 구조 정보 -->
<!ELEMENT answerrules (fixed*, required*, optional*)>

<!-- fixed 형식의 avp rule -->
<!ELEMENT fixed (avprule+)>
<!-- required 형식의 avp rule -->
<!ELEMENT required (avprule+)>
<!-- optional 형식의 avp rule -->
<!ELEMENT optional (avprule+)>

<!-- AVP rule 정보 -->
<!ELEMENT avprule EMPTY>
<!ATTLIST avprule
	name IDREF #REQUIRED <!-- avp의 이름 -->
	maximum CDATA "none" <!-- 가질 수 있는 최대 AVP의 개수 -->
	minimum CDATA "0" <!-- 가져야 하는 최소 AVP의 개수 -->
	max CDATA "none" <!-- 가질 수 있는 최대 AVP의 개수 -->
	min CDATA "0" <!-- 가져야 하는 최소 AVP의 개수 -->
	trace_id CDATA #IMPLIED  <!-- 해당 AVP가 trace id로 사용될것인지 여부 -->
>

<!-- base application (IETF 기본 : app_id=0) 정보들 -->
<!ELEMENT base (command*, typedef+, avp+)>
<!ATTLIST base
	uri CDATA #IMPLIED <!-- base application specification uri -->
>

<!-- application 정보들 -->
<!ELEMENT application (command*, typedef*, avp*)>
<!ATTLIST application
	id CDATA #REQUIRED <!-- application id -->
	name CDATA #IMPLIED <!-- application name 또는 interface name -->
	uri CDATA #IMPLIED <!-- application specification uri -->
>

<!-- command 정보 -->
<!ELEMENT command (requestrules*, answerrules*)>
<!ATTLIST command
	name CDATA #REQUIRED <!-- command 이름 -->
	code CDATA #REQUIRED <!-- command code -->
	application-id CDATA #IMPLIED <!-- 사용할 application-id -->
	abbreviation CDATA #IMPLIED <!-- command 이름 축약형 -->
	proxiable ("yes" | "no" | "true" | "false" | "on" | "off") "yes" <!-- proxying 가능한지 여부. (default : yes) -->
	description CDATA #IMPLIED <!-- command 에 대한 설명 -->
>

=== cacalos/JTEtest/usmsf_map/data/data_sig/dict/dict_3gpp_Rx_TS29214.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "dictionary.dtd">

<dictionary>

	<!-- ************* DIAMETER Rx APPLICATION ************* -->
	<application id="16777236" name="Rx" uri="http://www.3gpp.org/DynaReport/29214.htm">
		<command name="AA" code="265" application-id="16777236" abbreviation="AA">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Destination-Host" maximum="1"/>
					<avprule name="IP-Domain-Id" maximum="1"/>
					<avprule name="AF-Application-Identifier" maximum="1"/>
					<avprule name="Media-Component-Description"/>
					<avprule name="Service-Info-Status" maximum="1"/>
					<avprule name="AF-Charging-Identifier" maximum="1"/>
					<avprule name="SIP-Forking-Indication" maximum="1"/>
					<avprule name="Specific-Action"/>
					<avprule name="Subscription-Id" trace_id="yes"/>
					<avprule name="Supported-Features"/>
					<avprule name="Reservation-Priority" maximum="1"/>
					<avprule name="Framed-IP-Address" maximum="1"/>
					<avprule name="Framed-IPv6-Prefix" maximum="1"/>
					<avprule name="Called-Station-Id" maximum="1"/>
					<avprule name="Service-URN" maximum="1"/>
					<avprule name="Sponsored-Connectivity-Data" maximum="1"/>
					<avprule name="MPS-Identifier" maximum="1"/>
					<avprule name="Rx-Request-Type" maximum="1"/>
					<avprule name="Required-Access-Info"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Result-Code" maximum="1" />
					<avprule name="Experimental-Result" maximum="1" />
					<avprule name="Access-Network-Charging-Identifier"/>
					<avprule name="Access-Network-Charging-Address" maximum="1" />
					<avprule name="Acceptable-Service-Info" maximum="1" />
					<avprule name="IP-CAN-Type" maximum="1" />
					<avprule name="NetLoc-Access-Support" maximum="1" />
					<avprule name="RAT-Type" maximum="1" />
					<avprule name="Flows" />
					<avprule name="Supported-Features" />
					<avprule name="Class" />
					<avprule name="Error-Message" maximum="1" />
					<avprule name="Error-Reporting-Host" maximum="1" />
					<avprule name="Failed-AVP" />
					<avprule name="Origin-State-Id" maximum="1" />
					<avprule name="Redirect-Host"/>
					<avprule name="Redirect-Host-Usage" maximum="1" />
					<avprule name="Redirect-Max-Cache-Time" maximum="1" />
					<avprule name="Proxy-Info"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>

		<command name="Re-Auth" code="258" application-id="16777236" abbreviation="RA">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Host" maximum="1" minimum="1"/>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
					<avprule name="Specific-Action" minimum="1"/>
				</required>
				<optional>
					<avprule name="Access-Network-Charging-Identifier"/>
					<avprule name="Access-Network-Charging-Address" maximum="1"/>
					<avprule name="Flows" />
					<avprule name="Subscription-Id" trace_id="yes"/>
					<avprule name="Abort-Cause" maximum="1"/>
					<avprule name="IP-CAN-Type" maximum="1"/>
					<avprule name="NetLoc-Access-Support" maximum="1"/>
					<avprule name="RAT-Type" maximum="1"/>
					<avprule name="Sponsored-Connectivity-Data" maximum="1"/>
					<avprule name="3GPP-User-Location-Info" maximum="1"/>
					<avprule name="User-Location-Info-Time" maximum="1"/>
					<avprule name="3GPP-MS-TimeZone" maximum="1"/>
					<avprule name="3GPP-SGSN-MCC-MNC" maximum="1"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Class" />
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Result-Code" maximum="1" />
					<avprule name="Experimental-Result" maximum="1" />
					<avprule name="Media-Component-Description" />
					<avprule name="Service-URN" maximum="1" />
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Class" />
					<avprule name="Error-Message" maximum="1"/>
					<avprule name="Error-Reporting-Host" maximum="1"/>
					<avprule name="Redirect-Host"/>
					<avprule name="Redirect-Host-Usage" maximum="1"/>
					<avprule name="Redirect-Max-Cache-Time" maximum="1"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Proxy-Info"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>

		<command name="Session-Termination" application-id="16777236" code="275" abbreviation="ST">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
					<avprule name="Termination-Cause" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Destination-Host" maximum="1"/>
					<avprule name="Required-Access-Info"/>
					<avprule name="Class"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Result-Code" maximum="1" minimum="1"/>
					<avprule name="Error-Message" maximum="1"/>
					<avprule name="Error-Reporting-Host" maximum="1"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Sponsored-Connectivity-Data" maximum="1"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="3GPP-User-Location-Info" maximum="1"/>
					<avprule name="User-Location-Info-Time" maximum="1"/>
					<avprule name="3GPP-MS-TimeZone" maximum="1"/>
					<avprule name="3GPP-SGSN-MCC-MNC" maximum="1"/>
					<avprule name="NetLoc-Access-Support" maximum="1" />
					<avprule name="Class"/>
					<avprule name="Redirect-Host"/>
					<avprule name="Redirect-Host-Usage" maximum="1"/>
					<avprule name="Redirect-Max-Cache-Time" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>
		<command name="Abort-Session" code="274" application-id="16777236" abbreviation="AS">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Host" maximum="1" minimum="1"/>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Abort-Cause" maximum="1"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Result-Code" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="User-Name" maximum="1"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Error-Message" maximum="1"/>
					<avprule name="Error-Reporting-Host" maximum="1"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Redirect-Host"/>
					<avprule name="Redirect-Host-Usage" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>
	</application>
</dictionary>

=== cacalos/JTEtest/usmsf_map/data/data_dia/dict/dict_ietf_nas_RFC4005.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE dictionary SYSTEM "dictionary.dtd"> -->

<dictionary>

	<!-- ************* DIAMETER NASREQ APPLICATION ************* -->
	<application id="1" name="NASREQ" uri="http://www.ietf.org/rfc/rfc4005.txt">
		<command name="AA" code="265" application-id="1" abbreviation="AA">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="Auth-Request-Type" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Destination-Host" maximum="1"/>
					<avprule name="NAS-Identifier" maximum="1" />
					<avprule name="NAS-IP-Address" maximum="1" />
					<avprule name="NAS-IPv6-Address" maximum="1" />
					<avprule name="NAS-Port" maximum="1"/>
					<avprule name="NAS-Port-Id" maximum="1" />
					<avprule name="NAS-Port-Type" maximum="1" />
					<avprule name="Origin-AAA-Protocol" maximum="1" />
					<avprule name="Origin-State-Id" maximum="1" />
					<avprule name="Port-Limit" maximum="1" />
					<avprule name="User-Name" maximum="1" />
					<avprule name="User-Password" maximum="1" />
					<avprule name="NAS-Service-Type" maximum="1" />
					<avprule name="State" maximum="1" />
					<avprule name="Authorization-Lifetime" maximum="1" />
					<avprule name="Auth-Grace-Period" maximum="1" />
					<avprule name="Auth-Session-State" maximum="1" />
					<avprule name="Callback-Number" maximum="1" />
					<avprule name="Called-Station-Id" maximum="1" />
					<avprule name="Calling-Station-Id" maximum="1" />
					<avprule name="Originating-Line-Info" maximum="1" />
					<avprule name="Connect-Info" maximum="1" />
					<avprule name="CHAP-Auth" maximum="1" />
					<avprule name="CHAP-Challenge" maximum="1" />
					<avprule name="Framed-Compression"/>
					<avprule name="Framed-Interface-Id" maximum="1" />
					<avprule name="Framed-IP-Address" maximum="1" />
					<avprule name="Framed-IPv6-Prefix"/>
					<avprule name="Framed-IP-Netmask" maximum="1" />
					<avprule name="Framed-MTU" maximum="1" />
					<avprule name="Framed-Protocol" maximum="1" />
					<avprule name="ARAP-Password" maximum="1" />
					<avprule name="ARAP-Security" maximum="1" />
					<avprule name="ARAP-Security-Data"/>
					<avprule name="Login-IP-Host"/>
					<avprule name="Login-IPv6-Host"/>
					<avprule name="Login-LAT-Group" maximum="1" />
					<avprule name="Login-LAT-Node" maximum="1" />
					<avprule name="Login-LAT-Port" maximum="1" />
					<avprule name="Login-LAT-Service" maximum="1" />
					<avprule name="Tunneling"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
					<avprule name="Auth-Request-Type" maximum="1" minimum="1"/>
					<avprule name="Result-Code" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="User-Name" maximum="1" />
					<avprule name="NAS-Service-Type" maximum="1" />
					<avprule name="Class"/>
					<avprule name="Configuration-Token"/>
					<avprule name="Acct-Interim-Interval" maximum="1" />
					<avprule name="Error-Message" maximum="1" />
					<avprule name="Error-Reporting-Host" maximum="1" />
					<avprule name="Failed-AVP"/>
					<avprule name="Idle-Timeout" maximum="1" />
					<avprule name="Authorization-Lifetime" maximum="1" />
					<avprule name="Auth-Grace-Period" maximum="1" />
					<avprule name="Auth-Session-State" maximum="1" />
					<avprule name="Re-Auth-Request-Type" maximum="1" />
					<avprule name="Multi-Round-Time-Out" maximum="1" />
					<avprule name="Session-Timeout" maximum="1" />
					<avprule name="State" maximum="1" />
					<avprule name="Reply-Message"/>
					<avprule name="Origin-AAA-Protocol"/>
					<avprule name="Origin-State-Id" maximum="1" />
					<avprule name="Filter-Id"/>
					<avprule name="Password-Retry" maximum="1" />
					<avprule name="Port-Limit" maximum="1" />
					<avprule name="Prompt" maximum="1" />
					<avprule name="ARAP-Challenge-Response" maximum="1" />
					<avprule name="ARAP-Features" maximum="1" />
					<avprule name="ARAP-Security" maximum="1" />
					<avprule name="ARAP-Security-Data"/>
					<avprule name="ARAP-Zone-Access" maximum="1" />
					<avprule name="Callback-Id" maximum="1" />
					<avprule name="Callback-Number" maximum="1" />
					<avprule name="Framed-Appletalk-Link" maximum="1" />
					<avprule name="Framed-Appletalk-Network"/>
					<avprule name="Framed-Appletalk-Zone" maximum="1" />
					<avprule name="Framed-Compression"/>
					<avprule name="Framed-Interface-Id" maximum="1" />
					<avprule name="Framed-IP-Address" maximum="1" />
					<avprule name="Framed-IPv6-Prefix"/>
					<avprule name="Framed-IPv6-Pool" maximum="1" />
					<avprule name="Framed-IPv6-Route"/>
					<avprule name="Framed-IP-Netmask" maximum="1" />
					<avprule name="Framed-Route"/>
					<avprule name="Framed-Pool" maximum="1" />
					<avprule name="Framed-IPX-Network" maximum="1" />
					<avprule name="Framed-MTU" maximum="1" />
					<avprule name="Framed-Protocol" maximum="1" />
					<avprule name="Framed-Routing" maximum="1" />
					<avprule name="Login-IP-Host"/>
					<avprule name="Login-IPv6-Host"/>
					<avprule name="Login-LAT-Group" maximum="1" />
					<avprule name="Login-LAT-Node" maximum="1" />
					<avprule name="Login-LAT-Port" maximum="1" />
					<avprule name="Login-LAT-Service" maximum="1" />
					<avprule name="Login-Service" maximum="1" />
					<avprule name="Login-TCP-Port" maximum="1" />
					<avprule name="NAS-Filter-Rule"/>
					<avprule name="QoS-Filter-Rule"/>
					<avprule name="Tunneling"/>
					<avprule name="Redirect-Host"/>
					<avprule name="Redirect-Host-Usage" maximum="1" />
					<avprule name="Redirect-Max-Cache-Time" maximum="1" />
					<avprule name="Proxy-Info"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>
	</application>

</dictionary>
