=== cacalos/JTEtest/usmsf_map/data/data_sig/dict/dictionary.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- dictionary configuration -->
<!ELEMENT dictionary (parser, display, vendor*, typedef*, error*, avp*, base, application*)>
     
<!-- uDIAMETER message parser option configuration 값 -->
<!ELEMENT parser (version, no_check_header_flag, check_unknown_cmd, check_unknown_avp,
				check_mandatory_avp_length, check_empty_group, check_avprule,
				check_required_length)>
<!ATTLIST parser
	version CDATA #IMPLIED <!-- DIAMETER message version (default : 1) -->
	<!-- DIAMETER Message Header Flag bits 값 오류를 체크하지 않는다. (default : no) -->
	no_check_header_flag ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- Unknown command 전달되었음을 체크할 것인지 여부 (default : no) -->
	check_unknown_cmd ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- Unknown AVP가 전달되었음 체크할 것인지 여부 (default : no) -->
	check_unknown_avp ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- Mandatory AVP의 길이가 0인지 체크할것인지 여부 (default : no) -->
	check_mandatory_avp_length ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- group이 empty일 경우 에러를 발생시킬 것인지 여부 (default : no) -->
	check_empty_group ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- avp rule을 사용해 avplist를 검증할 것인지 여부 (default : no) -->
	check_avprule ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- required AVP의 길이가 0인지 체크할것인지 여부 (default : no) -->
	check_required_length ("yes" | "no" | "true" | "false" | "on" | "off") "no"
>
<!ELEMENT version (#PCDATA)> <!-- DIAMETER message version (default : 1) -->
<!ELEMENT no_check_header_flag (#PCDATA)> <!-- DIAMETER Message Header Flag bits 값 오류를 체크하지 않는다. (default : no) -->
<!ELEMENT check_unknown_cmd (#PCDATA)> <!-- Unknown command 전달되었음을 체크할 것인지 여부 (default : no) -->
<!ELEMENT check_unknown_avp (#PCDATA)> <!-- Unknown AVP가 전달되었음 체크할 것인지 여부 (default : no) -->
<!ELEMENT check_mandatory_avp_length (#PCDATA)> <!-- Mandatory AVP의 길이가 0인지 체크할것인지 여부 (default : no) -->
<!ELEMENT check_empty_group (#PCDATA)> <!-- group이 empty일 경우 에러를 발생시킬 것인지 여부 (default : no) -->
<!ELEMENT check_avprule (#PCDATA)> <!-- avp rule을 사용해 avplist를 검증할 것인지 여부 (default : no) -->
<!ELEMENT check_required_length (#PCDATA)> <!-- required AVP의 길이가 0인지 체크할것인지 여부 (default : no) -->

<!-- uDIAMETER message display option --> 
<!ELEMENT display (tabsize, octnbline, octflags, timeformat)>,
<!ATTLIST display
	tabsize CDATA #IMPLIED <!-- avp depth 별 tab 크기 (default : 0 [TAB 사용])-->
	octnbline CDATA #IMPLIED <!-- octet의 한줄당 byte 출력 개수 (default : 16) -->
	<!-- octet 출력 flags (0x01: number disable, 0x02: ascii disable, 0x04: newline char)  (default : 0x03) -->
	octflags CDATA #IMPLIED
	<!-- time value 출력 format. 특수 문자가 들어가므로 CDATA로 표기할 것을 권함 (default : %Y-%m-%dT%H:%H:%S) -->
	timeformat CDATA #IMPLIED
>
<!ELEMENT tabsize EMPTY> <!-- avp depth 별 tab 크기 (default : 0 [TAB 사용])-->
<!ELEMENT octnbline EMPTY> <!-- octet의 한줄당 byte 출력 개수 (default : 16) --> 
<!-- octet 출력 flags (0x01: number disable, 0x02: ascii disable, 0x04: newline char)  (default : 0x03) -->
<!ELEMENT octflags EMPTY> 
<!-- time value 출력 format. 특수 문자가 들어가므로 CDATA로 표기할 것을 권함 (default : %Y-%m-%dT%H:%H:%S) -->
<!ELEMENT timeformat EMPTY>

<!-- vendor id 정보 -->
<!ELEMENT vendor EMPTY>
<!ATTLIST vendor
	id CDATA #REQUIRED <!-- vendor id (ex: 10415) -->
	name CDATA #REQUIRED <!-- vendor name (ex: 3GPP) -->
>

<!-- type definition 정보 --> 
<!ELEMENT typedef EMPTY>
<!ATTLIST typedef
	name ID #REQUIRED <!-- type 이름 -->
	parent IDREF #IMPLIED <!-- 부모 type 이름 -->
>

<!-- error definition 정보 --> 
<!ELEMENT error EMPTY>
<!ATTLIST error
	code CDATA #REQUIRED <!-- error code -->
	name ID #REQUIRED <!-- error 이름 -->
>

<!-- AVP definition 정보 -->
<!ELEMENT avp ((type | grouped | enumerated))>
<!ATTLIST avp
	name ID #REQUIRED <!-- AVP 이름 -->
	code CDATA #REQUIRED <!-- AVP code -->
	vendor_id CDATA #IMPLIED <!-- AVP vendor id -->
	mandatory (must | may | mustnot | shouldnot) "may" <!-- mandatory 여부 -->
	protected (must | may | mustnot | shouldnot) "may" <!-- protected 여부 -->
	<!-- 출력 옵션 (hexstr: STRING일 경우 HEX값 형태로 출력, hexval: 출력 시 HEX 값도 같이 출력,
			rsltcode : 해당 int 값의 result code 이름도 같이 출력)  -->
	display (default | hexstr | hexval | rsltcode) "default"
	description CDATA #IMPLIED <!-- avp 에 대한 설명 -->
>
<!-- AVP type 정보 -->
<!ELEMENT type EMPTY>
<!ATTLIST type
	name IDREF #REQUIRED <!-- AVP type 이름 -->
>
<!-- AVP group 타입에 구조 정보 -->
<!ELEMENT grouped (fixed*, required*, optional*)>
<!-- AVP enumerated 타입에 대한 정보 -->
<!ELEMENT enumerated (enum*)>
<!-- AVP enum 멤버에 대한 정보 -->
<!ELEMENT enum EMPTY>
<!ATTLIST enum
	name CDATA #REQUIRED <!-- enum name -->
	code CDATA #IMPLIED <!-- enum code value -->
>

<!-- request message 구조 정보 -->
<!ELEMENT requestrules (fixed*, required*, optional*)>
<!-- answer message 구조 정보 -->
<!ELEMENT answerrules (fixed*, required*, optional*)>

<!-- fixed 형식의 avp rule -->
<!ELEMENT fixed (avprule+)>
<!-- required 형식의 avp rule -->
<!ELEMENT required (avprule+)>
<!-- optional 형식의 avp rule -->
<!ELEMENT optional (avprule+)>

<!-- AVP rule 정보 -->
<!ELEMENT avprule EMPTY>
<!ATTLIST avprule
	name IDREF #REQUIRED <!-- avp의 이름 -->
	maximum CDATA "none" <!-- 가질 수 있는 최대 AVP의 개수 -->
	minimum CDATA "0" <!-- 가져야 하는 최소 AVP의 개수 -->
	max CDATA "none" <!-- 가질 수 있는 최대 AVP의 개수 -->
	min CDATA "0" <!-- 가져야 하는 최소 AVP의 개수 -->
	trace_id CDATA #IMPLIED  <!-- 해당 AVP가 trace id로 사용될것인지 여부 -->
>

<!-- base application (IETF 기본 : app_id=0) 정보들 -->
<!ELEMENT base (command*, typedef+, avp+)>
<!ATTLIST base
	uri CDATA #IMPLIED <!-- base application specification uri -->
>

<!-- application 정보들 -->
<!ELEMENT application (command*, typedef*, avp*)>
<!ATTLIST application
	id CDATA #REQUIRED <!-- application id -->
	name CDATA #IMPLIED <!-- application name 또는 interface name -->
	uri CDATA #IMPLIED <!-- application specification uri -->
>

<!-- command 정보 -->
<!ELEMENT command (requestrules*, answerrules*)>
<!ATTLIST command
	name CDATA #REQUIRED <!-- command 이름 -->
	code CDATA #REQUIRED <!-- command code -->
	application-id CDATA #IMPLIED <!-- 사용할 application-id -->
	abbreviation CDATA #IMPLIED <!-- command 이름 축약형 -->
	proxiable ("yes" | "no" | "true" | "false" | "on" | "off") "yes" <!-- proxying 가능한지 여부. (default : yes) -->
	description CDATA #IMPLIED <!-- command 에 대한 설명 -->
>

=== cacalos/JTEtest/usmsf_map/data/data_dia/dict/dict_3gpp_GiSGi_TS29061.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "dictionary.dtd">

<dictionary>

<!-- TS 29.061-840: Interworking between the PLMN supporting packet based services and PDN -->
<!-- ************* DIAMETER GiSGi Application ************* -->
<application id="1" name="Gi/SGi" uri="http://www.3gpp.org/DynaReport/29061.htm">
	<command name="AA" abbreviation="AA" code="265" applicatoin-id="1" proxiable="1">
		<requestrules>
			<!--TODO-->
		</requestrules>
		<answerrules>
			<!--TODO-->
		</answerrules>
	</command>
	<command name="Accounting" abbreviation="AC" code="271" applicatoin-id="3" proxiable="1">
		<requestrules>
			<!--TODO-->
		</requestrules>
		<answerrules>
			<!--TODO-->
		</answerrules>
	</command>
	<command name="Session-Termination" abbreviation="ST" code="275" applicatoin-id="0" proxiable="1">
		<requestrules>
			<!--TODO-->
		</requestrules>
		<answerrules>
			<!--TODO-->
		</answerrules>
	</command>
	<command name="Abort-Session" abbreviation="AA" code="274" application-id="0" proxiable="1">
		<requestrules>
			<!--TODO-->
		</requestrules>
		<answerrules>
			<!--TODO-->
		</answerrules>
	</command>
</application>

</dictionary>

=== cacalos/JTEtest/usmsf_map/data/data_sig/dict/dict_3gpp_T4_TS29337.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "dictionary.dtd">

<dictionary>
	<!-- ************* DIAMETER T4 APPLICATION ************* -->
	<!-- TS 29.337-d20: Diameter-based T4 interface for communications with packet data networks and applications -->

	<application id="16777311" name="T4" uri="http://www.3gpp.org/DynaReport/29337.htm">
		<command name="Device-Trigger-Request" code="8388643" abbreviation="DT" application-id="16777311" proxiable="yes">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Session-State" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="User-Identifier" maximum="1" minimum="1" trace_id="true"/>
					<avprule name="SM-RP-SMEA" maximum="1" minimum="1"/>
					<avprule name="Payload" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="DRMP" maximum="1"/>
					<avprule name="Destination-Host" maximum="1"/>
					<avprule name="Serving-Node" maximum="1"/>
					<avprule name="Additional-Serving-Node" maximum="1"/>
					<avprule name="Reference-Number" maximum="1"/>
					<avprule name="Validity-Time" maximum="1"/>
					<avprule name="Priority-Indication" maximum="1"/>
					<!--
					<avprule name="Application-Port-Identifier" maximum="1"/>
					-->
					<avprule name="SMS-Application-Port-ID" maximum="1"/>
					<avprule name="Old-Reference-Number" maximum="1"/>
					<avprule name="Trigger-Action" maximum="1"/>
					<avprule name="Supported-Features"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Session-State" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="DRMP" maximum="1"/>
					<avprule name="Vendor-Specific-Application-Id" maximum="1"/>
					<avprule name="Result-Code" maximum="1"/>
					<avprule name="Experimental-Result" maximum="1"/>
					<avprule name="MTC-Error-Diagnostic" maximum="1"/>
					<avprule name="Old-Reference-Number" maximum="1"/>
					<avprule name="Trigger-Action" maximum="1"/>
					<avprule name="Supported-Features"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>
		<command name="Delivery-Report" code="8388644" abbreviation="DR" application-id="16777311" proxiable="yes">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Session-State" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Host" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="User-Identifier" maximum="1" minimum="1"/>
					<avprule name="SM-RP-SMEA" maximum="1" minimum="1"/>
					<avprule name="SM-Delivery-Outcome-T4" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="DRMP" maximum="1"/>
					<avprule name="Absent-Subscriber-Diagnostic-T4" maximum="1"/>
					<avprule name="Reference-Number" maximum="1"/>
					<avprule name="Supported-Features"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Session-State" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="DRMP" maximum="1"/>
					<avprule name="Vendor-Specific-Application-Id" maximum="1"/>
					<avprule name="Result-Code" maximum="1"/>
					<avprule name="Experimental-Result" maximum="1"/>
					<avprule name="Supported-Features"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>
	</application>
</dictionary>

=== cacalos/JTEtest/usmsf_map/data/data_dia/dict/dict_3gpp_Gmb_TS29061.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "dictionary.dtd">

<dictionary>

<!-- TS 29.061-840: Interworking between the PLMN supporting packet based services and PDN -->
<!-- ************* DIAMETER Gmb Application ************* -->
<application id="16777223" name="Gmb" uri="http://www.3gpp.org/DynaReport/29061.htm">
	<command name="AA" abbreviation="AA" code="265" applicatoin-id="0">
		<requestrules>
			<!--TODO-->
		</requestrules>
		<answerrules>
			<!--TODO-->
		</answerrules>
	</command>
	<command name="ST" abbreviation="ST" code="275" applicatoin-id="0">
		<requestrules>
			<!--TODO-->
		</requestrules>
		<answerrules>
			<!--TODO-->
		</answerrules>
	</command>
	<command name="Re-Auth" abbreviation="RA" code="275" applicatoin-id="0">
		<requestrules>
			<!--TODO-->
		</requestrules>
		<answerrules>
			<!--TODO-->
		</answerrules>
	</command>
	<command name="Abort-Session" abbreviation="AS" code="275" applicatoin-id="0">
		<requestrules>
			<!--TODO-->
		</requestrules>
		<answerrules>
			<!--TODO-->
		</answerrules>
	</command>
</application>

</dictionary>

=== cacalos/JTEtest/usmsf_map/data/data_sig/dict/dict_3gpp_S6c_TS29338.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "dictionary.dtd">

<dictionary>

	<!-- ************* DIAMETER S6c APPLICATION ************* -->
	<application id="16777312" name="S6c" uri="http://www.3gpp.org/DynaReport/29273.htm">
		<command name="Send-Routing-Info-for-SM" code="8388647" application-id="16777312" abbreviation="SR">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Session-State" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
                    <avprule name="Destination-Host" maximum="1" minimum="1"/>
				</required>
				<optional>
                    <avprule name="Vendor-Specific-Application-Id" maximum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="MSISDN" maximum="1"/>
					<avprule name="User-Name" maximum="1" trace_id="userid"/>
					<avprule name="SC-Address" maximum="1" minimum="1"/>
					<avprule name="SM-RP-MTI" maximum="1" minimum="1"/>
					<avprule name="SM-RP-SMEA" maximum="1" minimum="1"/>
					<avprule name="SRR-Flags" maximum="1" minimum="1"/>
					<avprule name="SM-Delivery-Not-Intended" maximum="1" minimum="1"/>
					<avprule name="DRMP" maximum="1"/>
					<avprule name="Supported-Features" />
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Session-State" maximum="1" />
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
   				<optional>
					<avprule name="DRMP" maximum="1"/>
                    <avprule name="Vendor-Specific-Application-Id" maximum="1"/>
					<avprule name="Result-Code" maximum="1" minimum="1"/>
					<avprule name="Experimental-Result" maximum="1" minimum="1"/>
					<avprule name="User-Name" maximum="1"/>
					<avprule name="Serving-Node" maximum="1"/>
					<avprule name="Additional-Serving-Node" maximum="1"/>
					<avprule name="LMSI" maximum="1" />
					<avprule name="User-Identifier" maximum="1" minimum="1"/>
					<avprule name="MWD-Status" maximum="1" minimum="1"/>
					<avprule name="MME-Absent-User-Diagnostic-SM" maximum="1" minimum="1"/>
					<avprule name="MSC-Absent-User-Diagnostic-SM" maximum="1" minimum="1"/>
					<avprule name="SGSN-Absent-User-Diagnostic-SM" maximum="1" minimum="1"/>
					<avprule name="AVP"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
				</optional>
			</answerrules>
		</command>
		<command name="Alert-Service-Centre-Request" code="8388648" application-id="16777312" proxiable="1">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Session-State" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="SC-Address" maximum="1" minimum="1"/>
					<avprule name="User-Identifier" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="DRMP" maximum="1"/>
					<avprule name="Vendor-Specific-Application-Id" maximum="1"/>
					<avprule name="Destination-Host" maximum="1"/>
					<avprule name="SMSMI-Correlation-ID" maximum="1"/>
					<avprule name="Maximum-UE-Availability-Time" maximum="1"/>
					<avprule name="SMS-GMSC-Alert-Event" maximum="1"/>
					<avprule name="Serving-Node" maximum="1"/>
					<avprule name="Supported-Features"/>
					<avprule name="Route-Record"/>
					<avprule name="Proxy-Info"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Session-State" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="DRMP" maximum="1"/>
					<avprule name="Vendor-Specific-Application-Id" maximum="1"/>
					<avprule name="Result-Code" maximum="1"/>
					<avprule name="Experimental-Result" maximum="1"/>
					<avprule name="Supported-Features"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>
		<command name="Report-SM-Delivery-Status" code="8388649" application-id="16777312" abbreviation="RD">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Session-State" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="User-Identifier" maximum="1" minimum="1"/>
					<avprule name="SC-Address" maximum="1" minimum="1"/>
					<avprule name="SM-Delivery-Outcome" maximum="1" minimum="1"/>
				</required>
				<optional>
                    <avprule name="Vendor-Specific-Application-Id" maximum="1"/>
                    <avprule name="Destination-Host" maximum="1" minimum="1"/>
					<avprule name="Supported-Features" />
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Session-State" maximum="1" />
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
   				<optional>
					<avprule name="DRMP" maximum="1"/>
                    <avprule name="Vendor-Specific-Application-Id" maximum="1"/>
					<avprule name="Result-Code" maximum="1" minimum="1"/>
					<avprule name="Experimental-Result" maximum="1" minimum="1"/>
					<avprule name="User-Identifier" maximum="1" minimum="1"/>
					<avprule name="Supported-Features" />
					<avprule name="AVP"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
				</optional>
			</answerrules>
		</command>
	</application>
</dictionary>

=== cacalos/JTEtest/usmsf_map/data/data_sig/dict/dict_common.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "dictionary.dtd">

<dictionary>
	<!-- ************************* Vendors **************************** -->
	<vendor id="0" name="IETF" />
	<vendor id="11" name="Hewlett Packard" />
	<vendor id="61" name="Merit Networks" />
	<vendor id="42" name="Sun Microsystems, Inc." />
	<vendor id="429" name="US Robotics Corp." />
	<vendor id="5535" name="3GPP2" />
	<vendor id="10415" name="3GPP" />
	<vendor id="193" name="Ericsson" />
	<vendor id="13019" name="ETSI" />
	<vendor id="12645" name="Vodafone" />
	<vendor id="14380" name="KT" />
	<vendor id="11858" name="UANGEL" />
	<!-- *********************** End Vendors ************************** -->

	<!-- ************************ typedef's ************************ -->
	<typedef name="OctetString"/>
	<typedef name="Integer32"/>
	<typedef name="Integer64"/>
	<typedef name="Unsigned32"/>
	<typedef name="Unsigned64"/>
	<typedef name="Float32"/>
	<typedef name="Float64"/>

	<typedef name="Address" parent="OctetString"/>
	<typedef name="Time" parent="OctetString"/>
	<typedef name="UTF8String" parent="OctetString"/>
	<typedef name="DiameterIdentity" parent="OctetString"/>
	<typedef name="DiameterURI" parent="UTF8String"/>
	<typedef name="Enumerated" parent="Unsigned32"/>
	<typedef name="IPFilterRule" parent="OctetString"/>
	<typedef name="QOSFilterRule" parent="OctetString"/>
	<!-- *********************** End Typedef ********************** -->

	<!-- extension error define -->
	<!--error code="7000" name="Example Error"/-->

	<!-- dictionary message parsing option --> 
	<parser>
		<!-- DIAMETER message version - optional(default:1) -->
		<!--version>1</version-->
		<!-- Whether or not to check DIAMETER Message Header Flag bits validity. (default : no) -->
		<!--no_check_header_flag>no</no_check_header_flag-->
		<!-- Whether to check Unknown command receiving. (default : no) -->
		<!--check_unknown_cmd>no</check_unknown_cmd-->
		<!-- Whether to check Unknown AVP receiving. (default : no) -->
		<!--check_unknown_avp>no</check_unknown_avp-->
		<!-- Whether to check that Mandatory AVP data length is 0. (default : no) -->
		<!--check_mandatory_avp_length>no</check_mandatory_avp_length-->
		<!-- Whether to raise error for empty group. (default : no) -->
		<!--check_empty_group>no</check_empty_group-->
		<!-- Wheter to check avplist validity by avp rule. (default : no) -->
		<!--check_avprule>no</check_avprule-->
		<!-- Whether to check that required AVP data length is 0. (default : no) -->
		<!--check_required_length>no</check_required_length-->
	</parser>

	<!-- dictionary message display option --> 
	<display>
		<!-- tab size for avp depth (default : 0 [TAB »ç¿ë]) -->
		<!--tabsize>0</tabsize-->
		<!-- byte number of a line of octet data (default : 16) -->
		<!--octnbline>16</octnbline-->
		<!-- octet displa flags (0x01: number disable, 0x02: ascii disable, 0x04: newline char)  (default : 0x03) -->
		<!--octflags>0x03</octflags-->
		<!-- time value display format. (default : %Y-%m-%dT%H:%H:%S) -->
		<!--timeformat><![CDATA[%Y-%m-%dT%H:%H:%S]]></timeformat-->
	</display>

	<base uri="http://www.ietf.org/rfc/rfc3588.txt">
		<avp name="Unknown-Avp" code="0" mandatory="must" may-encrypt="yes" display="HEXSTR">
			<type name="OctetString"/>
		</avp>
		<command name="Unknown-Command" abbreviation="UC" code="0" proxiable="0">
			<requestrules>
				<optional>
					<avprule name="Session-Id"/>
					<avprule name="Origin-Host"/>
					<avprule name="Origin-Realm"/>
					<avprule name="Destination-Realm"/>
					<avprule name="Destination-Host"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<optional>
					<avprule name="Session-Id"/>
					<avprule name="Result-Code"/>
					<avprule name="Origin-Host"/>
					<avprule name="Origin-Realm"/>
					<avprule name="Error-Message"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Proxy-Info"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>
	</base>
</dictionary>
