=== cacalos/JTEtest/usmsf_map/data/data_sig/dict/dictionary.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- dictionary configuration -->
<!ELEMENT dictionary (parser, display, vendor*, typedef*, error*, avp*, base, application*)>
     
<!-- uDIAMETER message parser option configuration 값 -->
<!ELEMENT parser (version, no_check_header_flag, check_unknown_cmd, check_unknown_avp,
				check_mandatory_avp_length, check_empty_group, check_avprule,
				check_required_length)>
<!ATTLIST parser
	version CDATA #IMPLIED <!-- DIAMETER message version (default : 1) -->
	<!-- DIAMETER Message Header Flag bits 값 오류를 체크하지 않는다. (default : no) -->
	no_check_header_flag ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- Unknown command 전달되었음을 체크할 것인지 여부 (default : no) -->
	check_unknown_cmd ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- Unknown AVP가 전달되었음 체크할 것인지 여부 (default : no) -->
	check_unknown_avp ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- Mandatory AVP의 길이가 0인지 체크할것인지 여부 (default : no) -->
	check_mandatory_avp_length ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- group이 empty일 경우 에러를 발생시킬 것인지 여부 (default : no) -->
	check_empty_group ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- avp rule을 사용해 avplist를 검증할 것인지 여부 (default : no) -->
	check_avprule ("yes" | "no" | "true" | "false" | "on" | "off") "no"
	<!-- required AVP의 길이가 0인지 체크할것인지 여부 (default : no) -->
	check_required_length ("yes" | "no" | "true" | "false" | "on" | "off") "no"
>
<!ELEMENT version (#PCDATA)> <!-- DIAMETER message version (default : 1) -->
<!ELEMENT no_check_header_flag (#PCDATA)> <!-- DIAMETER Message Header Flag bits 값 오류를 체크하지 않는다. (default : no) -->
<!ELEMENT check_unknown_cmd (#PCDATA)> <!-- Unknown command 전달되었음을 체크할 것인지 여부 (default : no) -->
<!ELEMENT check_unknown_avp (#PCDATA)> <!-- Unknown AVP가 전달되었음 체크할 것인지 여부 (default : no) -->
<!ELEMENT check_mandatory_avp_length (#PCDATA)> <!-- Mandatory AVP의 길이가 0인지 체크할것인지 여부 (default : no) -->
<!ELEMENT check_empty_group (#PCDATA)> <!-- group이 empty일 경우 에러를 발생시킬 것인지 여부 (default : no) -->
<!ELEMENT check_avprule (#PCDATA)> <!-- avp rule을 사용해 avplist를 검증할 것인지 여부 (default : no) -->
<!ELEMENT check_required_length (#PCDATA)> <!-- required AVP의 길이가 0인지 체크할것인지 여부 (default : no) -->

<!-- uDIAMETER message display option --> 
<!ELEMENT display (tabsize, octnbline, octflags, timeformat)>,
<!ATTLIST display
	tabsize CDATA #IMPLIED <!-- avp depth 별 tab 크기 (default : 0 [TAB 사용])-->
	octnbline CDATA #IMPLIED <!-- octet의 한줄당 byte 출력 개수 (default : 16) -->
	<!-- octet 출력 flags (0x01: number disable, 0x02: ascii disable, 0x04: newline char)  (default : 0x03) -->
	octflags CDATA #IMPLIED
	<!-- time value 출력 format. 특수 문자가 들어가므로 CDATA로 표기할 것을 권함 (default : %Y-%m-%dT%H:%H:%S) -->
	timeformat CDATA #IMPLIED
>
<!ELEMENT tabsize EMPTY> <!-- avp depth 별 tab 크기 (default : 0 [TAB 사용])-->
<!ELEMENT octnbline EMPTY> <!-- octet의 한줄당 byte 출력 개수 (default : 16) --> 
<!-- octet 출력 flags (0x01: number disable, 0x02: ascii disable, 0x04: newline char)  (default : 0x03) -->
<!ELEMENT octflags EMPTY> 
<!-- time value 출력 format. 특수 문자가 들어가므로 CDATA로 표기할 것을 권함 (default : %Y-%m-%dT%H:%H:%S) -->
<!ELEMENT timeformat EMPTY>

<!-- vendor id 정보 -->
<!ELEMENT vendor EMPTY>
<!ATTLIST vendor
	id CDATA #REQUIRED <!-- vendor id (ex: 10415) -->
	name CDATA #REQUIRED <!-- vendor name (ex: 3GPP) -->
>

<!-- type definition 정보 --> 
<!ELEMENT typedef EMPTY>
<!ATTLIST typedef
	name ID #REQUIRED <!-- type 이름 -->
	parent IDREF #IMPLIED <!-- 부모 type 이름 -->
>

<!-- error definition 정보 --> 
<!ELEMENT error EMPTY>
<!ATTLIST error
	code CDATA #REQUIRED <!-- error code -->
	name ID #REQUIRED <!-- error 이름 -->
>

<!-- AVP definition 정보 -->
<!ELEMENT avp ((type | grouped | enumerated))>
<!ATTLIST avp
	name ID #REQUIRED <!-- AVP 이름 -->
	code CDATA #REQUIRED <!-- AVP code -->
	vendor_id CDATA #IMPLIED <!-- AVP vendor id -->
	mandatory (must | may | mustnot | shouldnot) "may" <!-- mandatory 여부 -->
	protected (must | may | mustnot | shouldnot) "may" <!-- protected 여부 -->
	<!-- 출력 옵션 (hexstr: STRING일 경우 HEX값 형태로 출력, hexval: 출력 시 HEX 값도 같이 출력,
			rsltcode : 해당 int 값의 result code 이름도 같이 출력)  -->
	display (default | hexstr | hexval | rsltcode) "default"
	description CDATA #IMPLIED <!-- avp 에 대한 설명 -->
>
<!-- AVP type 정보 -->
<!ELEMENT type EMPTY>
<!ATTLIST type
	name IDREF #REQUIRED <!-- AVP type 이름 -->
>
<!-- AVP group 타입에 구조 정보 -->
<!ELEMENT grouped (fixed*, required*, optional*)>
<!-- AVP enumerated 타입에 대한 정보 -->
<!ELEMENT enumerated (enum*)>
<!-- AVP enum 멤버에 대한 정보 -->
<!ELEMENT enum EMPTY>
<!ATTLIST enum
	name CDATA #REQUIRED <!-- enum name -->
	code CDATA #IMPLIED <!-- enum code value -->
>

<!-- request message 구조 정보 -->
<!ELEMENT requestrules (fixed*, required*, optional*)>
<!-- answer message 구조 정보 -->
<!ELEMENT answerrules (fixed*, required*, optional*)>

<!-- fixed 형식의 avp rule -->
<!ELEMENT fixed (avprule+)>
<!-- required 형식의 avp rule -->
<!ELEMENT required (avprule+)>
<!-- optional 형식의 avp rule -->
<!ELEMENT optional (avprule+)>

<!-- AVP rule 정보 -->
<!ELEMENT avprule EMPTY>
<!ATTLIST avprule
	name IDREF #REQUIRED <!-- avp의 이름 -->
	maximum CDATA "none" <!-- 가질 수 있는 최대 AVP의 개수 -->
	minimum CDATA "0" <!-- 가져야 하는 최소 AVP의 개수 -->
	max CDATA "none" <!-- 가질 수 있는 최대 AVP의 개수 -->
	min CDATA "0" <!-- 가져야 하는 최소 AVP의 개수 -->
	trace_id CDATA #IMPLIED  <!-- 해당 AVP가 trace id로 사용될것인지 여부 -->
>

<!-- base application (IETF 기본 : app_id=0) 정보들 -->
<!ELEMENT base (command*, typedef+, avp+)>
<!ATTLIST base
	uri CDATA #IMPLIED <!-- base application specification uri -->
>

<!-- application 정보들 -->
<!ELEMENT application (command*, typedef*, avp*)>
<!ATTLIST application
	id CDATA #REQUIRED <!-- application id -->
	name CDATA #IMPLIED <!-- application name 또는 interface name -->
	uri CDATA #IMPLIED <!-- application specification uri -->
>

<!-- command 정보 -->
<!ELEMENT command (requestrules*, answerrules*)>
<!ATTLIST command
	name CDATA #REQUIRED <!-- command 이름 -->
	code CDATA #REQUIRED <!-- command code -->
	application-id CDATA #IMPLIED <!-- 사용할 application-id -->
	abbreviation CDATA #IMPLIED <!-- command 이름 축약형 -->
	proxiable ("yes" | "no" | "true" | "false" | "on" | "off") "yes" <!-- proxying 가능한지 여부. (default : yes) -->
	description CDATA #IMPLIED <!-- command 에 대한 설명 -->
>

=== cacalos/JTEtest/usmsf_map/data/data_sig/dict/dict_ietf_base_RFC6733.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE dictionary SYSTEM "dictionary.dtd"> -->

<dictionary>
	<!-- ***************** Base Protocol Definition ******************* -->
	<base uri="http://www.ietf.org/rfc/rfc6733.txt">
		<!-- *********************** Commands *************************** -->
		<!-- Diameter Base Protocol Command Codes -->
		<command name="Capabilities-Exchange" code="257" abbreviation="CE" proxiable="false">
			<requestrules>
				<required>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Host-IP-Address" minimum="1"/>
					<avprule name="Vendor-Id" maximum="1" minimum="1"/>
					<avprule name="Product-Name" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Supported-Vendor-Id"/>
					<avprule name="Auth-Application-Id"/>
					<avprule name="Acct-Application-Id"/>
					<avprule name="Vendor-Specific-Application-Id"/>
					<avprule name="Firmware-Revision" maximum="1"/>
					<avprule name="Inband-Security-Id" maximum="1"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<required>
					<avprule name="Result-Code" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Host-IP-Address" minimum="1"/>
					<avprule name="Vendor-Id" maximum="1" minimum="1"/>
					<avprule name="Product-Name" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Error-Message" maximum="1"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Supported-Vendor-Id"/>
					<avprule name="Auth-Application-Id"/>
					<avprule name="Acct-Application-Id"/>
					<avprule name="Vendor-Specific-Application-Id"/>
					<avprule name="Firmware-Revision" maximum="1"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>

		<command name="Device-Watchdog" code="280" abbreviation="DW" proxiable="false">
			<requestrules>
				<required>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Origin-State-Id" maximum="1"/>
				</optional>
			</requestrules>
			<answerrules>
				<required>
					<avprule name="Result-Code" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Error-Message" maximum="1"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Origin-State-Id" maximum="1"/>
				</optional>
			</answerrules>
		</command>

		<command name="Disconnect-Peer" code="282" abbreviation="DP" proxiable="false">
			<requestrules>
				<required>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Disconnect-Cause" maximum="1" minimum="1"/>
				</required>
			</requestrules>
			<answerrules>
				<required>
					<avprule name="Result-Code" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Error-Message" maximum="1"/>
					<avprule name="Failed-AVP"/>
				</optional>
			</answerrules>
		</command>

		<command name="Re-Auth" code="258" abbreviation="RA">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Host" maximum="1" minimum="1"/>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
					<avprule name="Re-Auth-Request-Type" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="User-Name" maximum="1"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Result-Code" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="User-Name" maximum="1"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Error-Message" maximum="1"/>
					<avprule name="Error-Reporting-Host" maximum="1"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Redirect-Host"/>
					<avprule name="Redirect-Host-Usage" maximum="1"/>
					<avprule name="Redirect-Max-Cache-Time" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>

		<!-- Diameter Base Protocol Abort-Session Command -->
		<command name="Abort-Session" code="274" abbreviation="AS" proxiable="true">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Host" maximum="1" minimum="1"/>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="User-Name" maximum="1"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="AVP"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Result-Code" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="User-Name" maximum="1"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Error-Message" maximum="1"/>
					<avprule name="Error-Reporting-Host" maximum="1"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Redirect-Host"/>
					<avprule name="Redirect-Host-Usage" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>

		<command name="Session-Termination" code="275" abbreviation="ST" proxiable="true">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
					<avprule name="Termination-Cause" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="User-Name" maximum="1"/>
					<avprule name="Destination-Host" maximum="1"/>
					<avprule name="Class"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Result-Code" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="User-Name" maximum="1"/>
					<avprule name="Class"/>
					<avprule name="Error-Message" maximum="1"/>
					<avprule name="Error-Reporting-Host" maximum="1"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Redirect-Host"/>
					<avprule name="Redirect-Host-Usage" maximum="1"/>
					<avprule name="Redirect-Max-Cache-Time" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>

		<!-- ********************** End Commands ************************ -->
	</base>
	<!-- ************** END DIAMETER BASE PROTOCOL AVPS ************* -->

</dictionary>

=== cacalos/JTEtest/usmsf_map/data/data_dia/dict/dict_3gpp_Sy_TS29219.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "dictionary.dtd">

<dictionary>

	<!-- ************* DIAMETER SY APPLICATION ************* -->
	<application id="16777302" name="Sy" uri="http://www.3gpp.org/DynaReport/29219.htm">
		<command name="Spending-Limit" code="8388635" abbreviation="SL">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Destination-Host" maximum="1"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="SL-Request-Type" maximum="1"/>
					<avprule name="Subscription-Id" trace_id="yes"/>
					<avprule name="Policy-Counter-Identifier"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Result-Code" maximum="1"/>
					<avprule name="Experimental-Result" maximum="1"/>
					<avprule name="Policy-Counter-Status-Report"/>
					<avprule name="Error-Message" maximum="1"/>
					<avprule name="Error-Reporting-Host" maximum="1"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Redirect-Host"/>
					<avprule name="Redirect-Host-Usage" maximum="1"/>
					<avprule name="Redirect-Max-Cache-Time" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>

		<command name="Spending-Status-Notification" code="8388636" abbreviation="SSN">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Destination-Host" maximum="1"/>
					<avprule name="Subscription-Id" trace_id="yes"/>  <!-- It needs confirm to DataBillingPlatform Team -->
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Policy-Counter-Status-Report"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Result-Code" maximum="1"/>
					<avprule name="Experimental-Result" maximum="1"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Error-Message" maximum="1"/>
					<avprule name="Error-Reporting-Host" maximum="1"/>
					<avprule name="Redirect-Host"/>
					<avprule name="Redirect-Host-Usage" maximum="1"/>
					<avprule name="Redirect-Max-Cache-Time" maximum="1"/>
					<avprule name="Failed-AVP"/>
					<avprule name="Proxy-Info"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>
	</application>
</dictionary>

=== cacalos/JTEtest/usmsf_map/data/data_dia/dict/dict_ietf_mip4_RFC4004.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE dictionary SYSTEM "dictionary.dtd"> -->

<dictionary>
	<!-- *********** DIAMETERE MOBILEIPV4 APPLICATION ***********-->
	<application id="2" name="Mobile IPv4" uri="http://www.ietf.org/rfc/rfc4004.txt">

		<command name="AA-Mobile-Node" code="260" application-id="2" proxiable="1">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
					<avprule name="User-Name" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="MIP-Reg-Request" maximum="1" minimum="1"/>
					<avprule name="MIP-MN-AAA-Auth" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Acct-Multi-Session-Id" maximum="1"/>
					<avprule name="Destination-Host" maximum="1"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="MIP-Mobile-Node-Address" maximum="1"/>
					<avprule name="MIP-Home-Agent-Address" maximum="1"/>
					<avprule name="MIP-Feature-Vector" maximum="1"/>
					<avprule name="MIP-Originating-Foreign-AAA" maximum="1"/>
					<avprule name="Authorization-Lifetime" maximum="1"/>
					<avprule name="Auth-Session-State" maximum="1"/>
					<avprule name="MIP-FA-Challenge" maximum="1"/>
					<avprule name="MIP-Candidate-Home-Agent-Host" maximum="1"/>
					<avprule name="MIP-Home-Agent-Host" maximum="1"/>
					<avprule name="MIP-HA-to-FA-SPI" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
					<avprule name="Result-Code" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Acct-Multi-Session-Id" maximum="1"/>
					<avprule name="User-Name" maximum="1"/>
					<avprule name="Authorization-Lifetime" maximum="1"/>
					<avprule name="Auth-Session-State" maximum="1"/>
					<avprule name="Error-Message" maximum="1"/>
					<avprule name="Error-Reporting-Host" maximum="1"/>
					<avprule name="Re-Auth-Request-Type" maximum="1"/>
					<avprule name="MIP-Feature-Vector" maximum="1"/>
					<avprule name="MIP-Reg-Reply" maximum="1"/>
					<avprule name="MIP-MN-to-FA-MSA" maximum="1"/>
					<avprule name="MIP-MN-to-HA-MSA" maximum="1"/>
					<avprule name="MIP-FA-to-MN-MSA" maximum="1"/>
					<avprule name="MIP-FA-to-HA-MSA" maximum="1"/>
					<avprule name="MIP-HA-to-MN-MSA" maximum="1"/>
					<avprule name="MIP-HA-to-FA-MSA" maximum="1"/>
					<avprule name="MIP-MSA-Lifetime" maximum="1"/>
					<avprule name="MIP-Home-Agent-Address" maximum="1"/>
					<avprule name="MIP-Mobile-Node-Address" maximum="1"/>
					<avprule name="MIP-Filter-Rule"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>

		<command name="Home-Agent-MIP" code="262" application-id="2" proxiable="1">
			<requestrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
					<avprule name="Authorization-Lifetime" maximum="1" minimum="1"/>
					<avprule name="Auth-Session-State" maximum="1" minimum="1"/>
					<avprule name="MIP-Reg-Request" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
					<avprule name="User-Name" maximum="1" minimum="1"/>
					<avprule name="Destination-Realm" maximum="1" minimum="1"/>
					<avprule name="MIP-Feature-Vector" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Destination-Host" maximum="1"/>
					<avprule name="MIP-MN-to-HA-MSA" maximum="1"/>
					<avprule name="MIP-MN-to-FA-MSA" maximum="1"/>
					<avprule name="MIP-HA-to-MN-MSA" maximum="1"/>
					<avprule name="MIP-HA-to-FA-MSA" maximum="1"/>
					<avprule name="MIP-MSA-Lifetime" maximum="1"/>
					<avprule name="MIP-Originating-Foreign-AAA" maximum="1"/>
					<avprule name="MIP-Mobile-Node-Address" maximum="1"/>
					<avprule name="MIP-Home-Agent-Address" maximum="1"/>
					<avprule name="MIP-Filter-Rule"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="Route-Record"/>
					<avprule name="AVP"/>
				</optional>
			</requestrules>
			<answerrules>
				<fixed>
					<avprule name="Session-Id" maximum="1" minimum="1"/>
				</fixed>
				<required>
					<avprule name="Auth-Application-Id" maximum="1" minimum="1"/>
					<avprule name="Result-Code" maximum="1" minimum="1"/>
					<avprule name="Origin-Host" maximum="1" minimum="1"/>
					<avprule name="Origin-Realm" maximum="1" minimum="1"/>
				</required>
				<optional>
					<avprule name="Acct-Multi-Session-Id" maximum="1"/>
					<avprule name="User-Name" maximum="1"/>
					<avprule name="Error-Reporting-Host" maximum="1"/>
					<avprule name="Error-Message" maximum="1"/>
					<avprule name="MIP-Reg-Reply" maximum="1"/>
					<avprule name="MIP-Home-Agent-Address" maximum="1"/>
					<avprule name="MIP-Mobile-Node-Address" maximum="1"/>
					<avprule name="MIP-FA-to-HA-SPI" maximum="1"/>
					<avprule name="MIP-FA-to-MN-SPI" maximum="1"/>
					<avprule name="Origin-State-Id" maximum="1"/>
					<avprule name="Proxy-Info"/>
					<avprule name="AVP"/>
				</optional>
			</answerrules>
		</command>

  </application>
</dictionary>
